local _PhrasesList = {
	"DA is literally better than IY",
	"hot ui gamers yessir yessir",
	"give me synapse now",
	"how's life?",
	"if u read this have a good day",
	"ur cool",
	"hey vsauce michael here",
	"hey vsauce michael here, today we are using DA",
	"I have ascended",
	"evolution and the Bible are hurting my brain",
	"where am I?",
	"ur whitelist key is jk there is none lmaooaeofiair",
	"save me from this hell hole called furry land",
	"what",
	"bit.ly/3gV1kmL",
	"I have no oxygen",
	"the backrooms is a great concept for a movie",
	"the americans took our rice again",
	"creeper, aw man, so we back in theaif hqeiorhgierwn",
	"timezones are annoying",
	"every timezone is atleast an hour apart from the ones beside them",
	"what is the meaning to life? the answer is said to be 42. it's based on a movie",
	"heyyyyy",
	"no sharing oki",
	"help, I've fallen and I can't get up!",
	"where is my burger?",
	"what is that tall black creature idk probably a spider- AAAAAAA",
	"top 10 famous last words: mlg water bucket into a volcano",
	"EA Sports, copying and pasting games are what they do!",
	"haeden's name in chinese comes out as hayden LOL F",
	"my dad came back after getting milk, took 25 minutes tho",
	"if you read this then how??",
	"idk",
	"a narwhal's tusk reveals its past living conditions",
	"\"New car smell\" is the scent of dozens of chemicals",
	"the first person convicted of speeding was going eight miles per hour",
	"the heads on Easter Island have bodies wtf bro",
	"humans are the only animals that blush. wait, did you just say animal?",
	"yo did you know that rabbits can't puke?",
	"the human body literally glows because of protons lmao",
	"dirty or infected door knob? get a copper door knob! they are self-disinfecting",
	"cotton candy was invented by a dentist",
	"chewing gum boosts concentration",
        "to be considered a millionaire nowadays, you need 2.5 million dollars",
	"https://infinite.store.likesyou.org/",
	"among us is a good game, its a murder mystery game, except the memes can be cringe tho",
	"a man survived biting a dorito chip sideways",
	"bro I stepped on a lego and I wish I died instead",
	"lol I clipped into the backrooms",
	"whitelist key: #############",
	"reminder: you are a gigachad",
	"all fax, no printer",
	"DA v2 releases after v9.9.9, after that, no update will be logged by it's version :O",
	"the Earl of Sandwich (John Montagu) invented the sandwich so he wouldn’t have to leave his gambling table to eat",
	"a narwhal's tusk reveals its past living conditions",
	"a pig's scientific name is \"sus\"",
	"some sea snakes can breathe through their skin",
	"the heads on Easter Island have bodies lmao",
	"The moon has \"moonquakes\" LOL",
	"it took 570 gallons to paint the exterior of the White House",
	"we shake hands to show we’re unarmed xd",
	"professional genshin impact player more like professional child groomer",
	"zwolf (a dev of iy) is a chad tbh",
	"your dad is sus",
	"decode what this will be used for: 7fjhi",
	"atp zombie stands for \"a toilet plunger zombie\"",
	"https://www.reddit.com/r/memes/",
	"discord.com/login can be easily gone to by using discord's shortened URL: dis.gd/login",
	"among us memes are cringe, among us is just a good murder mystery space themed game",
	"vape v4 exists on roblox (its also in the scripts tab lol)",
	"have a good day",
	"how to not be a simp, by dr. antisimp: chapter 1, page 1: to not be a simp you have to not simp",
	"no comment"
}
return tostring(_PhrasesList[math.random(1, #_PhrasesList)])
